[theme]
base = "light"
primaryColor = "#3346A8"
backgroundColor = "#F5F7FB"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#16213E"
font = "sans serif"

[server]
maxUploadSize = 20
enableStaticServing = false
runOnSave = true

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"